### ISSUE TITLE
When doing download , Invalid arguments

### ISSUE THREAD

**Issue by Ferouden** [YongHaoWu/NeteaseCloudMusicFlac#15]
```bash
Traceback (most recent call last):
  File "python3_main.py", line 69, in <module>
    with open(filename, "wb") as code:
OSError: [Errno 22] Invalid argument: 'D:\\music download flac-ape\\NeteaseCloudMusicFlac-master/songs_dir/The Godfather Main Theme "The Godfather Waltz" (From "The Godfather")-The Original Movies Orchestra.flac'
```

**Comment by Ferouden** [comment]
Seems because the file name has invalid characters?

**Comment by YongHaoWu** [comment]
Yep, I think so. Maybe we need to strip the space before saving files.

**Comment by szclsya** [comment]
Same problem. Waiting for solution.

**Comment by YongHaoWu** [comment]
@Ferouden @szclsya I will start to solve this problem tonight.
@szclsya Please give me your Netease song list url.

**Comment by szclsya** [comment]
@YongHaoWu Sorry for the late reply.
This problem occurs on my Windows 10 with Linux sub-system installed. Today I tried it on my laptop with Arch Linux installed and the problem disappers. I think it could be caused by the system, but not your program.
By the way, when trying on my Linux, I discover that few of the songs of the list can be downloaded. (Actually most download sources are from Baidu lol) Please keep developing, this is a brilliant program!
P.S: The list I used to test: [http://music.163.com/playlist?id=93230949](url)

**Comment by YongHaoWu** [comment]
@szclsya 
Hi, thank you for your support.
Maybe it is that Windows do not support that file name, we still need to strip special characters.
Hum, it is normal that a few songs can be downloaded as it is not popular.
You can also develop this program and make merge request ; P

**Comment by YongHaoWu** [comment]
@Ferouden @szclsya 
Hi, I 've already fixed this issue. Plz check https://github.com/YongHaoWu/NeteaseCloudMusicFlac/commit/bbb0b2738e0582eb867c9a0e352c4c042327ad71

**Comment by szclsya** [comment]
@YongHaoWu Got it. Getting ready for exams these days, may test later. : (

**Comment by YongHaoWu** [comment]
@szclsya Sure, look forward to your good news. :P

**Comment by YongHaoWu** [comment]
@szclsya Are u free now? ;P

**Comment by szclsya** [comment]
@YongHaoWu 
Sorry for the (very) late reply...
I checked this program in a later version of Windows 10(I reinstalled my desktop computer), and it worked just fine.
Thank you for your work!
