### ISSUE TITLE
how to use this?

### ISSUE THREAD

**Issue by zyndin** [YongHaoWu/NeteaseCloudMusicFlac#23]
Could you write how to use typhon to download music?

I did this guide. But not work.
https://github.com/BurntSushi/nfldb/wiki/Python-&-pip-Windows-installation

Thanks in advance.

**Comment by YongHaoWu** [comment]
@zyndin hi, can you read Chinese?  I have a doc written in Chinese.

**Comment by zyndin** [comment]
@YongHaoWu Hello, No, I can't. But you can write with Chinese I will use Google translate to my language.

Thank you for your replying.

**Comment by YongHaoWu** [comment]
@zyndin  LOL, I don't think that there is a foreigner interested about this.
This is a tool to download FLAC music from the list you created from http://music.163.com/ 
When u create a list like this, you can use python to run my script, so that it will download automatically.

**Comment by zyndin** [comment]
I have an acount at music.163.com, can listen albums. But I want to download some albums with FLAC and I search on google and saw your tools that I don't know how to use it with python.

Could you record step by step how to use this amazing tool, please?

**Comment by YongHaoWu** [comment]
Sure, good to hear that you can use it.
First, install Python 2.7 or python 3. (You can search how on Google).
Second, find you song list's URL, e.g: http://music.163.com/#/playlist?id=979850767
Third, download this: https://github.com/YongHaoWu/NeteaseCloudMusicFlac/archive/master.zip

Extract the file,  then use main.py if you are using Python2.7, python3_main.py for Python3.
Input the command:(Find how to run python script on Google, the file you download is my  script)

` python main.py 'http://music.163.com/#/playlist?id=145258012'

Or

` python3 python3_main.py 'http://music.163.com/#/playlist?id=145258012'`


Note that the URL after the main.py is the song list on music.163.com that you want to download.


At last, when you execute the command, the song will start to download.
Flac files are on the scripts ' directory, on `songs_dir` directory.


Since you may not a programmer, it 's a little hard to use this.
Anyway, if you have problems, please let me know.

Hope that you can enjoy it.

**Comment by zyndin** [comment]
Thank you so much. 
I will do follow your guide. I will try my best to use this tool although it's so hard.

Before I search a software call name is 音乐间谍V3.4 and now it's not work now. :(

**Comment by YongHaoWu** [comment]
@zyndin Hum,  音乐间谍 seems good. 
The reason I made this script is that though download flac in China is easy, but it needs to download one by one.

**Comment by zyndin** [comment]
@YongHaoWu 
It's hard to download flac in China.
I am researching to find out how to use your scritp :) Very hard for  me.

**Comment by zyndin** [comment]
@YongHaoWu Hello, 

May I ask you can get this album for me?

http://music.163.com/#/album?id=35569629

Thanks in advance.

**Comment by YongHaoWu** [comment]
@zyndin You can use http://imfangli.github.io/baidu-music-downloader/ this to search for FLAC, if you only want to download a few songs.

**Comment by zyndin** [comment]
@YongHaoWu Thank you so much. But I can't search the song that I want. :(

**Comment by YongHaoWu** [comment]
@zyndin  Hum, it's resources are not complete. You can find more popular songs  like You 're not along, Top of the world.
